#!/usr/bin/env bash

# Mọi giá trị bên dưới đều có thể ghi đè qua biến môi trường.
# Ví dụ: DISK_WARN=85 IOWAIT_WARN=25 ./linux-healthcheck.sh

# Thư mục lưu log và dữ liệu baseline.
HC_LOG_DIR="${HC_LOG_DIR:-/var/log/linux-healthcheck}"
HC_STATE_DIR="${HC_STATE_DIR:-/var/lib/linux-healthcheck}"

# CPU và load.
IOWAIT_WARN="${IOWAIT_WARN:-20}"
IOWAIT_CRIT="${IOWAIT_CRIT:-30}"
CPU_SAMPLE_SECONDS="${CPU_SAMPLE_SECONDS:-5}"
LOAD_WARN_PER_CORE="${LOAD_WARN_PER_CORE:-1.0}"
LOAD_CRIT_PER_CORE="${LOAD_CRIT_PER_CORE:-1.5}"

# Dung lượng filesystem và inode.
DISK_WARN="${DISK_WARN:-80}"
DISK_CRIT="${DISK_CRIT:-90}"
INODE_WARN="${INODE_WARN:-80}"
INODE_CRIT="${INODE_CRIT:-90}"

# Memory, swap và file descriptor.
MEM_AVAILABLE_WARN_PCT="${MEM_AVAILABLE_WARN_PCT:-15}"
MEM_AVAILABLE_CRIT_PCT="${MEM_AVAILABLE_CRIT_PCT:-8}"
SWAP_SAMPLE_COUNT="${SWAP_SAMPLE_COUNT:-5}"
SWAP_WARN_ACTIVE_SAMPLES="${SWAP_WARN_ACTIVE_SAMPLES:-2}"
SWAP_CRIT_ACTIVE_SAMPLES="${SWAP_CRIT_ACTIVE_SAMPLES:-4}"
FD_WARN="${FD_WARN:-70}"
FD_CRIT="${FD_CRIT:-80}"

# I/O. SSD/NVMe có độ trễ kỳ vọng thấp hơn HDD.
HDD_AWAIT_WARN_MS="${HDD_AWAIT_WARN_MS:-20}"
HDD_AWAIT_CRIT_MS="${HDD_AWAIT_CRIT_MS:-40}"
SSD_AWAIT_WARN_MS="${SSD_AWAIT_WARN_MS:-2}"
SSD_AWAIT_CRIT_MS="${SSD_AWAIT_CRIT_MS:-5}"
DISK_UTIL_WARN="${DISK_UTIL_WARN:-90}"
DISK_UTIL_CRIT="${DISK_UTIL_CRIT:-99}"

# Nhiệt độ và network.
TEMP_WARN="${TEMP_WARN:-80}"
TEMP_CRIT="${TEMP_CRIT:-90}"
TCP_RETRANS_WARN_PCT="${TCP_RETRANS_WARN_PCT:-1}"
TCP_RETRANS_CRIT_PCT="${TCP_RETRANS_CRIT_PCT:-2}"

# Baseline theo lịch sử chạy.
BASELINE_DAYS="${BASELINE_DAYS:-7}"
BASELINE_MIN_SAMPLES="${BASELINE_MIN_SAMPLES:-3}"
BASELINE_WARN_FACTOR="${BASELINE_WARN_FACTOR:-2.0}"
BASELINE_CRIT_FACTOR="${BASELINE_CRIT_FACTOR:-3.0}"
